name: Test Build

on:
  release:
    types: [created]

jobs:
  package-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    env:
      INCLUDE_PATHS: |
        assets/
        pack.mcmeta
        pack.png
        README.md

    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Prepare zip file
        run: |
          mkdir zip-root
          for path in $INCLUDE_PATHS; do
            cp -r --parents "$path" zip-root/
          done
          (cd zip-root && zip -r ../Modernity-GTNH-UI-${{ github.event.release.tag_name }}.zip .)
          rm -rf zip-root
        shell: bash

      - name: Upload files to release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            Modernity-GTNH-UI-${{ github.event.release.tag_name }}.zip
