name: Auto Commit Build

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      INCLUDE_PATHS: |
        assets/
        pack.mcmeta
        pack.png
        README.md

      TARGET_BRANCHES: "main"
      ZIP_NAME_main: "Modernity-GTNH-UI-{SHA}-pre.zip"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build all branches
        run: |
          for BRANCH in $TARGET_BRANCHES; do
            git checkout $BRANCH
            VAR_NAME="ZIP_NAME_${BRANCH//-/_}"
            ZIP_TEMPLATE="${!VAR_NAME}"
            ZIP_NAME="${ZIP_TEMPLATE//\{SHA\}/$SHORT_SHA}"

            rm -rf zip-root
            mkdir zip-root
            for path in $INCLUDE_PATHS; do
              if [ -e "$path" ]; then
                cp -r --parents "$path" zip-root/
              fi
            done
            cd zip-root
            zip -r "../$ZIP_NAME" ./
            cd ..
          done
        shell: bash
        env:
          INCLUDE_PATHS: ${{ env.INCLUDE_PATHS }}
          SHORT_SHA: ${{ env.SHORT_SHA }}
          ZIP_NAME_main: ${{ env.ZIP_NAME_main }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Commit ${{ env.SHORT_SHA }}
          tag_name: commit-${{ env.SHORT_SHA }}
          prerelease: false
          make_latest: true
          files: |
            Modernity-GTNH-UI-${{ env.SHORT_SHA }}-pre.zip
